# Generated by Django 3.2.8 on 2021-11-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batteryChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('current', models.PositiveBigIntegerField()),
                ('run_time', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='maxCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveBigIntegerField()),
                ('c_rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='batteryDetail',
        ),
    ]
