# Generated by Django 3.2.8 on 2021-11-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20211130_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='continuousCurr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveBigIntegerField()),
                ('c_rating', models.PositiveIntegerField()),
            ],
        ),
    ]
