# Generated by Django 3.2.8 on 2021-11-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_continuouscurr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuouscurr',
            name='c_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='maxcurrent',
            name='c_rating',
            field=models.FloatField(),
        ),
    ]
