# Generated by Django 3.2.8 on 2021-12-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_auto_20211201_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='burstCurr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveBigIntegerField()),
                ('c_rating', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='continuouscurr',
            name='c_rating',
        ),
        migrations.AddField(
            model_name='continuouscurr',
            name='continuous_current',
            field=models.FloatField(null=True),
        ),
    ]
