# Generated by Django 3.2.8 on 2021-12-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_auto_20211201_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='dischargeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_rating', models.FloatField()),
            ],
        ),
    ]
