# Generated by Django 3.2.8 on 2021-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batteryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_cells', models.PositiveIntegerField()),
                ('voltage', models.FloatField()),
                ('c_count', models.PositiveIntegerField()),
                ('mAh', models.PositiveBigIntegerField()),
            ],
        ),
    ]
